spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart-city
    username: root
    password: juan
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false